version: '3.8'
services:
  configserver:
    image: chanhenghong/configserver:latest
    mem_limit: 700m
    ports:
      - 8071:8071
    networks:
      - chanhenghongnet
  account:
    image: chanhenghong/account:latest
    mem_limit: 700m
    ports:
      - 8080:8080
    networks:
      - chanhenghongnet
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071
networks:
  chanhenghongnet:

    # Run docker compose: docker compose up
